### ISSUE TITLE
Chamfered Edge Connector?

### ISSUE THREAD

**Issue by oXL0C0Xo** [necroware/xt-prototyping-board#1]
The PCB manufacturer I have chosen (JLCPCB) is asking if the edge connector on this board should be chamfered. I’m concerned that if I have them chamfer the board, that the connector may end up too short. Do you know if this will be an issue? Is the board fine as designed without the chamfered edge connector? Thank you!

**Comment by necroware** [comment]
You don need it, ISA is wide enough to go without bevel.

**Comment by oXL0C0Xo** [comment]
Thank you!
